name: simple_pid
description: A simple PID controller. Ported from https://github.com/m-lundberg/simple-pid.
version: 1.0.2
repository: https://github.com/cthurston/simple-pid-dart

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.15.7
